<a href="https://colab.research.google.com/github/morekajal/Large_Language_Models_with_PyTorch/blob/main/06_nn_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### nn.Embedding module gives the embedding vectors of character/words/sentence

In [1]:
import torch
import torch.nn as nn

In [4]:
#Initialize an embedding layer
vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

#Create some input indices
input_indices = torch.LongTensor([1, 5, 3 ,2])

#Apply the embedding layer
embedded_output = embedding(input_indices)

#output_dim = no.of_input, dim_of_embedding_vectors
print(embedded_output.shape)

torch.Size([4, 100])


In [ ]:
print(embedded_output)


In [6]:
a = torch.tensor([[1, 2], [3, 4], [5 ,6]])
b = torch.tensor([[7, 8 , 9], [10, 11, 12]])
print( a @ b)     #torch dot product

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [7]:
# or

In [9]:
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [11]:
# In pytorch for multiplication -> variables should be on same type
int_64 = torch.randint(1, (3 ,2))
float_32 = torch.rand(2, 3)
result = torch.matmul(int_64, float_32)
print(result)

RuntimeError: ignored

In [12]:
# In such cases we can use variable_casting
int_64 = torch.randint(1, (3 ,2)).float()
float_32 = torch.rand(2, 3)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
